TEC-1644: Progress Bar
Evino/chablis pull request #39
Opened 2021-06-02 21:12 UTC by ocaioaugusto

2021-06-02 21:26 UTC, antoniojunyor requested changes

2021-06-02 21:26 UTC, antoniojunyor commented on src/components/ProgressBar/index.jsx
> +        left: 0px;
Replace `0px` to `0`

2021-06-02 21:26 UTC, antoniojunyor commented on src/components/ProgressBar/index.jsx
> +        content: "";
Use single quote

2021-06-02 21:26 UTC, antoniojunyor commented on src/components/ProgressBar/index.jsx
> +export const Bar = styled.span`
Maybe you can have a specific file to the `<Bar />` component, and another file to the `<ProgressBarStyled />`

2021-06-02 21:26 UTC, antoniojunyor commented on src/components/ProgressBar/index.jsx
> +      border: 3px solid #ec720b;
This color on border should be on variables?

2021-06-02 21:26 UTC, antoniojunyor commented on src/components/ProgressBar/index.jsx
> +  &:nth-child(1) {
Just a comment, you don't need the `&` ... just to you know.

2021-06-02 21:26 UTC, antoniojunyor commented on src/components/ProgressBar/index.jsx
> +export const ProgressBarContainer = styled.div`
Create a specific file to this component

2021-06-02 21:26 UTC, antoniojunyor commented on src/styles/variables.js
> +export const zIndexes = {
NICE!

2021-06-02 22:34 UTC, antoniojunyor approved these changes

2021-06-02 22:41 UTC, antoniojunyor approved these changes

2021-06-03 02:23 UTC, pserick commented
Tenta colocar a foto do component no pr pra ficar melhor pra analisar! 🙏🏽

2021-06-03 02:24 UTC, pserick approved these changes

2021-06-03 13:42 UTC, merged